/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { ApprovalProposal, UnifiedCosmosMsg } from './common'

export type Uint128 = string
export type DepositToken =
  | {
      token: {
        denom: UncheckedDenom
      }
    }
  | {
      voting_module_token: {
        token_type: VotingModuleTokenType
      }
    }
export type UncheckedDenom =
  | {
      native: string
    }
  | {
      cw20: string
    }
export type VotingModuleTokenType = 'native' | 'cw20'
export type DepositRefundPolicy = 'always' | 'only_passed' | 'never'
export type PreProposeSubmissionPolicy =
  | {
      anyone: {
        denylist: Addr[]
      }
    }
  | {
      specific: {
        allowlist: Addr[]
        dao_members: boolean
        denylist: Addr[]
      }
    }
export type Addr = string
export interface InstantiateMsg {
  deposit_info?: UncheckedDepositInfo | null
  extension: InstantiateExt
  /**
   * < v2.5.0
   */
  open_proposal_submission?: boolean
  /**
   * >= v2.5.0
   */
  submission_policy?: PreProposeSubmissionPolicy
}
export interface UncheckedDepositInfo {
  amount: Uint128
  denom: DepositToken
  refund_policy: DepositRefundPolicy
}
export interface InstantiateExt {
  approver: string
}
export type ExecuteMsg =
  | {
      propose: {
        msg: ProposeMessage
      }
    }
  | {
      update_config: {
        deposit_info?: UncheckedDepositInfo | null
        /**
         * < v2.5.0
         */
        open_proposal_submission?: boolean
        /**
         * >= v2.5.0
         */
        submission_policy?: PreProposeSubmissionPolicy | null
      }
    }
  | {
      update_submission_policy: {
        allowlist_add?: string[] | null
        allowlist_remove?: string[] | null
        denylist_add?: string[] | null
        denylist_remove?: string[] | null
        set_dao_members?: boolean | null
      }
    }
  | {
      withdraw: {
        denom?: UncheckedDenom | null
      }
    }
  | {
      extension: {
        msg: ApprovalExecuteExt
      }
    }
  | {
      add_proposal_submitted_hook: {
        address: string
      }
    }
  | {
      remove_proposal_submitted_hook: {
        address: string
      }
    }
  | {
      proposal_completed_hook: {
        new_status: Status
        proposal_id: number
      }
    }
export type ProposeMessage = {
  propose: {
    description: string
    msgs: UnifiedCosmosMsg[]
    title: string
    vote?: SingleChoiceAutoVote | null
  }
}
export type Binary = string
export type Timestamp = Uint64
export type Uint64 = string
export type Decimal = string
export type Vote = 'yes' | 'no' | 'abstain'
export type ApprovalExecuteExt =
  | {
      approve: {
        id: number
      }
    }
  | {
      reject: {
        id: number
      }
    }
  | {
      update_approver: {
        address: string
      }
    }
export type Status =
  | 'open'
  | 'rejected'
  | 'passed'
  | 'executed'
  | 'closed'
  | 'execution_failed'
  | {
      veto_timelock: {
        expiration: Expiration
      }
    }
  | 'vetoed'
export type Expiration =
  | {
      at_height: number
    }
  | {
      at_time: Timestamp
    }
  | {
      never: {}
    }
export interface Coin {
  amount: Uint128
  denom: string
}
export interface Empty {}
export interface SingleChoiceAutoVote {
  rationale?: string | null
  vote: Vote
}
export type QueryMsg =
  | {
      proposal_module: {}
    }
  | {
      dao: {}
    }
  | {
      info: {}
    }
  | {
      config: {}
    }
  | {
      deposit_info: {
        proposal_id: number
      }
    }
  | {
      can_propose: {
        address: string
      }
    }
  | {
      proposal_submitted_hooks: {}
    }
  | {
      query_extension: {
        msg: QueryExt
      }
    }
export type QueryExt =
  | {
      approver: {}
    }
  | {
      is_pending: {
        id: number
      }
    }
  | {
      proposal: {
        id: number
      }
    }
  | {
      pending_proposal: {
        id: number
      }
    }
  | {
      pending_proposals: {
        limit?: number | null
        start_after?: number | null
      }
    }
  | {
      reverse_pending_proposals: {
        limit?: number | null
        start_before?: number | null
      }
    }
  | {
      completed_proposal: {
        id: number
      }
    }
  | {
      completed_proposals: {
        limit?: number | null
        start_after?: number | null
      }
    }
  | {
      reverse_completed_proposals: {
        limit?: number | null
        start_before?: number | null
      }
    }
  | {
      completed_proposal_id_for_created_proposal_id: {
        id: number
      }
    }
export type MigrateMsg =
  | {
      from_under_v250: {
        policy?: PreProposeSubmissionPolicy | null
      }
    }
  | {
      extension: {
        msg: Empty
      }
    }
export type Boolean = boolean
export type CheckedDenom =
  | {
      native: string
    }
  | {
      cw20: Addr
    }
export interface Config {
  deposit_info?: CheckedDepositInfo | null
  /**
   * < v2.5.0
   */
  open_proposal_submission?: boolean
  /**
   * >= v2.5.0
   */
  submission_policy?: PreProposeSubmissionPolicy
}
export interface CheckedDepositInfo {
  amount: Uint128
  denom: CheckedDenom
  refund_policy: DepositRefundPolicy
}
export interface DepositInfoResponse {
  deposit_info?: CheckedDepositInfo | null
  proposer: Addr
}
export interface InfoResponse {
  info: ContractVersion
}
export interface ContractVersion {
  contract: string
  version: string
}
export interface HooksResponse {
  hooks: string[]
}
export type ProposalStatus =
  | {
      pending: {}
    }
  | {
      approved: {
        created_proposal_id: number
      }
    }
  | {
      rejected: {}
    }
export type ProposalStatusKey = 'pending' | 'approved' | 'rejected'
export type SingleChoiceProposeMsg = {
  title: string
  description: string
  msgs: UnifiedCosmosMsg[]
  proposer?: string | null
  vote?: SingleChoiceAutoVote | null
}
export type SingleChoiceApprovalProposal =
  ApprovalProposal<SingleChoiceProposeMsg>
