/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Uint64 = string
export interface InstantiateMsg {
  block_max_gas: Uint64
  contract_addr_len?: number | null
  proxy_code_id: Uint64
}
export type ExecuteMsg = {
  rx: {
    connection_id: string
    counterparty_port: string
    data: Binary
  }
}
export type Binary = string
export type QueryMsg =
  | 'block_max_gas'
  | 'proxy_code_id'
  | 'contract_addr_len'
  | {
      sender_info_for_proxy: {
        proxy: string
      }
    }
export type Uint8 = number
export interface SenderInfo {
  connection_id: string
  remote_port: string
  remote_sender: string
}
