/* tslint:disable */
import { Binary, Uint128 } from "./shared-types";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      bond: {
        [k: string]: unknown;
      };
    }
  | {
      unbond: {
        tokens: Uint128;
        [k: string]: unknown;
      };
    }
  | {
      claim: {
        [k: string]: unknown;
      };
    }
  | {
      update_admin: {
        admin?: string | null;
        [k: string]: unknown;
      };
    }
  | {
      add_hook: {
        addr: string;
        [k: string]: unknown;
      };
    }
  | {
      remove_hook: {
        addr: string;
        [k: string]: unknown;
      };
    }
  | {
      receive: Cw20ReceiveMsg;
    };

/**
 * Cw20ReceiveMsg should be de/serialized under `Receive()` variant in a ExecuteMsg
 */
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
