/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { selectorFamily } from 'recoil'

import { ValenceServiceRebalancerQueryClient } from '@dao-dao/state/contracts/ValenceServiceRebalancer'
import { WithChainId } from '@dao-dao/types'
import {
  RebalancerConfig,
  SystemRebalanceStatus,
} from '@dao-dao/types/contracts/ValenceServiceRebalancer'

import { cosmWasmClientForChainSelector } from '../chain'

type QueryClientParams = WithChainId<{
  contractAddress: string
}>

export const queryClient = selectorFamily<
  ValenceServiceRebalancerQueryClient,
  QueryClientParams
>({
  key: 'valenceServiceRebalancerQueryClient',
  get:
    ({ contractAddress, chainId }) =>
    ({ get }) => {
      const client = get(cosmWasmClientForChainSelector(chainId))
      return new ValenceServiceRebalancerQueryClient(client, contractAddress)
    },
  dangerouslyAllowMutability: true,
})

export const getConfigSelector = selectorFamily<
  RebalancerConfig,
  QueryClientParams & {
    params: Parameters<ValenceServiceRebalancerQueryClient['getConfig']>
  }
>({
  key: 'valenceServiceRebalancerGetConfig',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.getConfig(...params)
    },
})
export const getSystemStatusSelector = selectorFamily<
  SystemRebalanceStatus,
  QueryClientParams & {
    params: Parameters<ValenceServiceRebalancerQueryClient['getSystemStatus']>
  }
>({
  key: 'valenceServiceRebalancerGetSystemStatus',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.getSystemStatus(...params)
    },
})
