/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  cw20_token_address: string
  /**
   * Owner if none set to info.sender.
   */
  owner?: string | null
  [k: string]: unknown
}
