/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      port: {
        [k: string]: unknown
      }
    }
  | {
      list_channels: {
        [k: string]: unknown
      }
    }
  | {
      channel: {
        id: string
        [k: string]: unknown
      }
    }
