/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      curve_info: {
        [k: string]: unknown
      }
    }
  | {
      balance: {
        address: string
        [k: string]: unknown
      }
    }
  | {
      token_info: {
        [k: string]: unknown
      }
    }
  | {
      allowance: {
        owner: string
        spender: string
        [k: string]: unknown
      }
    }
