/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { UseQueryOptions, queryOptions } from '@tanstack/react-query'

import {
  Addr,
  Boolean,
  Config,
  DepositInfoResponse,
  HooksResponse,
  InfoResponse,
  QueryExt,
} from '@dao-dao/types/contracts/DaoPreProposeApprovalMultiple'
import { getCosmWasmClientForChainId } from '@dao-dao/utils'

import { DaoPreProposeApprovalMultipleQueryClient } from '../../../contracts/DaoPreProposeApprovalMultiple'
import { contractQueries } from '../contract'
import { indexerQueries } from '../indexer'

export const daoPreProposeApprovalMultipleQueryKeys = {
  contract: [
    {
      contract: 'daoPreProposeApprovalMultiple',
    },
  ] as const,
  address: (chainId: string, contractAddress: string) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.contract[0],
        chainId,
        address: contractAddress,
      },
    ] as const,
  proposalModule: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'proposal_module',
        args,
      },
    ] as const,
  dao: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'dao',
        args,
      },
    ] as const,
  info: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'info',
        args,
      },
    ] as const,
  config: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'config',
        args,
      },
    ] as const,
  depositInfo: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'deposit_info',
        args,
      },
    ] as const,
  canPropose: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'can_propose',
        args,
      },
    ] as const,
  proposalSubmittedHooks: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'proposal_submitted_hooks',
        args,
      },
    ] as const,
  queryExtension: (
    chainId: string,
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeApprovalMultipleQueryKeys.address(
          chainId,
          contractAddress
        )[0],
        method: 'query_extension',
        args,
      },
    ] as const,
}
export const daoPreProposeApprovalMultipleQueries = {
  proposalModule: <TData = Addr>({
    chainId,
    contractAddress,
    options,
  }: MultipleChoiceApprovalProposalModuleQuery<TData>) =>
    queryOptions<Addr, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.proposalModule(
        chainId,
        contractAddress
      ),
      queryFn: async (ctx) => {
        try {
          // Attempt to fetch data from the indexer.
          return await ctx.client.fetchQuery(
            indexerQueries.queryContract({
              chainId,
              contractAddress,
              formula: 'daoPreProposeApprovalMultiple/proposalModule',
            })
          )
        } catch (error) {
          console.error(error)
        }

        // If indexer query fails, fallback to contract query.
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).proposalModule()
      },
      ...options,
    }),
  dao: <TData = Addr>({
    chainId,
    contractAddress,
    options,
  }: DaoPreProposeApprovalMultipleDaoQuery<TData>) =>
    queryOptions<Addr, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.dao(
        chainId,
        contractAddress
      ),
      queryFn: async (ctx) => {
        try {
          // Attempt to fetch data from the indexer.
          return await ctx.client.fetchQuery(
            indexerQueries.queryContract({
              chainId,
              contractAddress,
              formula: 'daoPreProposeApprovalMultiple/dao',
            })
          )
        } catch (error) {
          console.error(error)
        }

        // If indexer query fails, fallback to contract query.
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).dao()
      },
      ...options,
    }),
  info: contractQueries.info,
  config: <TData = Config>({
    chainId,
    contractAddress,
    options,
  }: DaoPreProposeApprovalMultipleConfigQuery<TData>) =>
    queryOptions<Config, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.config(
        chainId,
        contractAddress
      ),
      queryFn: async (ctx) => {
        try {
          // Attempt to fetch data from the indexer.
          return await ctx.client.fetchQuery(
            indexerQueries.queryContract({
              chainId,
              contractAddress,
              formula: 'daoPreProposeApprovalMultiple/config',
            })
          )
        } catch (error) {
          console.error(error)
        }

        // If indexer query fails, fallback to contract query.
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).config()
      },
      ...options,
    }),
  depositInfo: <TData = DepositInfoResponse>({
    chainId,
    contractAddress,
    args,
    options,
  }: DaoPreProposeApprovalMultipleDepositInfoQuery<TData>) =>
    queryOptions<DepositInfoResponse, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.depositInfo(
        chainId,
        contractAddress,
        args
      ),
      queryFn: async (ctx) => {
        try {
          // Attempt to fetch data from the indexer.
          return await ctx.client.fetchQuery(
            indexerQueries.queryContract({
              chainId,
              contractAddress,
              formula: 'daoPreProposeApprovalMultiple/depositInfo',
              args: {
                proposalId: args.proposalId,
              },
            })
          )
        } catch (error) {
          console.error(error)
        }

        // If indexer query fails, fallback to contract query.
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).depositInfo({
          proposalId: args.proposalId,
        })
      },
      ...options,
    }),
  canPropose: <TData = Boolean>({
    chainId,
    contractAddress,
    args,
    options,
  }: DaoPreProposeApprovalMultipleCanProposeQuery<TData>) =>
    queryOptions<Boolean, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.canPropose(
        chainId,
        contractAddress,
        args
      ),
      queryFn: async () => {
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).canPropose({
          address: args.address,
        })
      },
      ...options,
    }),
  proposalSubmittedHooks: <TData = HooksResponse>({
    chainId,
    contractAddress,
    options,
  }: MultipleChoiceApprovalProposalSubmittedHooksQuery<TData>) =>
    queryOptions<HooksResponse, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.proposalSubmittedHooks(
        chainId,
        contractAddress
      ),
      queryFn: async () => {
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).proposalSubmittedHooks()
      },
      ...options,
    }),
  queryExtension: <TData = any>({
    chainId,
    contractAddress,
    args,
    options,
  }: DaoPreProposeApprovalMultipleQueryExtensionQuery<TData>) =>
    queryOptions<any, Error, TData>({
      queryKey: daoPreProposeApprovalMultipleQueryKeys.queryExtension(
        chainId,
        contractAddress,
        args
      ),
      queryFn: async (ctx) => {
        try {
          const query = args.msg
          if ('approver' in query) {
            const approver = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula: 'daoPreProposeApprovalMultiple/approver',
              })
            )
            if (approver) {
              return approver
            }
          } else if ('proposal' in query) {
            const proposal = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula: 'daoPreProposeApprovalMultiple/proposal',
                args: {
                  id: query.proposal.id,
                },
              })
            )
            if (proposal) {
              return proposal
            }
          } else if ('pending_proposals' in query) {
            const pendingProposals = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula: 'daoPreProposeApprovalMultiple/pendingProposals',
                args: {
                  limit: query.pending_proposals.limit,
                  startAfter: query.pending_proposals.start_after,
                },
              })
            )
            if (pendingProposals) {
              return pendingProposals
            }
          } else if ('reverse_pending_proposals' in query) {
            const reversePendingProposals = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula:
                  'daoPreProposeApprovalMultiple/reversePendingProposals',
                args: {
                  limit: query.reverse_pending_proposals.limit,
                  startBefore: query.reverse_pending_proposals.start_before,
                },
              })
            )
            if (reversePendingProposals) {
              return reversePendingProposals
            }
          } else if ('completed_proposals' in query) {
            const completedProposals = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula: 'daoPreProposeApprovalMultiple/completedProposals',
                args: {
                  limit: query.completed_proposals.limit,
                  startAfter: query.completed_proposals.start_after,
                },
              })
            )
            if (completedProposals) {
              return completedProposals
            }
          } else if ('reverse_completed_proposals' in query) {
            const reverseCompletedProposals = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula:
                  'daoPreProposeApprovalMultiple/reverseCompletedProposals',
                args: {
                  limit: query.reverse_completed_proposals.limit,
                  startBefore: query.reverse_completed_proposals.start_before,
                },
              })
            )
            if (reverseCompletedProposals) {
              return reverseCompletedProposals
            }
          } else if ('completed_proposal_id_for_created_proposal_id' in query) {
            const completedProposalId = await ctx.client.fetchQuery(
              indexerQueries.queryContract({
                chainId,
                contractAddress,
                formula:
                  'daoPreProposeApprovalMultiple/completedProposalIdForCreatedProposalId',
                args: {
                  id: query.completed_proposal_id_for_created_proposal_id.id,
                },
              })
            )
            if (completedProposalId) {
              return completedProposalId
            }
          }
        } catch (error) {
          console.error(error)
        }

        // If indexer query fails, fallback to contract query.
        return new DaoPreProposeApprovalMultipleQueryClient(
          await getCosmWasmClientForChainId(chainId),
          contractAddress
        ).queryExtension({
          msg: args.msg,
        })
      },
      ...options,
    }),
}
export interface DaoPreProposeApprovalMultipleReactQuery<
  TResponse,
  TData = TResponse,
> {
  chainId: string
  contractAddress: string
  options?: Omit<
    UseQueryOptions<TResponse, Error, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  > & {
    initialData?: undefined
  }
}
export interface DaoPreProposeApprovalMultipleQueryExtensionQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<any, TData> {
  args: {
    msg: QueryExt
  }
}
export interface MultipleChoiceApprovalProposalSubmittedHooksQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<HooksResponse, TData> {}
export interface DaoPreProposeApprovalMultipleCanProposeQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<Boolean, TData> {
  args: {
    address: string
  }
}
export interface DaoPreProposeApprovalMultipleDepositInfoQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<DepositInfoResponse, TData> {
  args: {
    proposalId: number
  }
}
export interface DaoPreProposeApprovalMultipleConfigQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<Config, TData> {}
export interface DaoPreProposeApprovalMultipleInfoQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<InfoResponse, TData> {}
export interface DaoPreProposeApprovalMultipleDaoQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<Addr, TData> {}
export interface MultipleChoiceApprovalProposalModuleQuery<TData>
  extends DaoPreProposeApprovalMultipleReactQuery<Addr, TData> {}
