/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { QueryClient, UseQueryOptions } from '@tanstack/react-query'

import {
  Addr,
  Binary,
  Boolean,
  Config,
  DepositInfoResponse,
  Empty,
  HooksResponse,
} from '@dao-dao/types/contracts/DaoPreProposeMultiple'
import { getCosmWasmClientForChainId } from '@dao-dao/utils'

import { DaoPreProposeMultipleQueryClient } from '../../../contracts/DaoPreProposeMultiple'
import { contractQueries } from '../contract'
import { indexerQueries } from '../indexer'

export const daoPreProposeMultipleQueryKeys = {
  contract: [
    {
      contract: 'daoPreProposeMultiple',
    },
  ] as const,
  address: (contractAddress: string) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.contract[0],
        address: contractAddress,
      },
    ] as const,
  proposalModule: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'proposal_module',
        args,
      },
    ] as const,
  dao: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'dao',
        args,
      },
    ] as const,
  config: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'config',
        args,
      },
    ] as const,
  depositInfo: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'deposit_info',
        args,
      },
    ] as const,
  canPropose: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'can_propose',
        args,
      },
    ] as const,
  proposalSubmittedHooks: (
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'proposal_submitted_hooks',
        args,
      },
    ] as const,
  queryExtension: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoPreProposeMultipleQueryKeys.address(contractAddress)[0],
        method: 'query_extension',
        args,
      },
    ] as const,
}
export const daoPreProposeMultipleQueries = {
  proposalModule: <TData = Addr>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      options,
    }: DaoPreProposeMultipleProposalModuleQuery<TData>
  ): UseQueryOptions<Addr, Error, TData> => ({
    queryKey: daoPreProposeMultipleQueryKeys.proposalModule(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoPreProposeMultiple/proposalModule',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposalModule()
    },
    ...options,
  }),
  dao: <TData = Addr>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: DaoPreProposeMultipleDaoQuery<TData>
  ): UseQueryOptions<Addr, Error, TData> => ({
    queryKey: daoPreProposeMultipleQueryKeys.dao(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoPreProposeMultiple/dao',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).dao()
    },
    ...options,
  }),
  config: <TData = Config>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      options,
    }: DaoPreProposeMultipleConfigQuery<TData>
  ): UseQueryOptions<Config, Error, TData> => ({
    queryKey: daoPreProposeMultipleQueryKeys.config(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoPreProposeMultiple/config',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).config()
    },
    ...options,
  }),
  depositInfo: <TData = DepositInfoResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoPreProposeMultipleDepositInfoQuery<TData>
  ): UseQueryOptions<DepositInfoResponse, Error, TData> => ({
    queryKey: daoPreProposeMultipleQueryKeys.depositInfo(contractAddress, args),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoPreProposeMultiple/depositInfo',
            args,
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).depositInfo({
        proposalId: args.proposalId,
      })
    },
    ...options,
  }),
  canPropose: <TData = Boolean>({
    chainId,
    contractAddress,
    args,
    options,
  }: DaoPreProposeMultipleCanProposeQuery<TData>): UseQueryOptions<
    Boolean,
    Error,
    TData
  > => ({
    queryKey: daoPreProposeMultipleQueryKeys.canPropose(contractAddress, args),
    queryFn: async () => {
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).canPropose({
        address: args.address,
      })
    },
    ...options,
  }),
  proposalSubmittedHooks: <TData = HooksResponse>({
    chainId,
    contractAddress,
    options,
  }: DaoPreProposeMultipleProposalSubmittedHooksQuery<TData>): UseQueryOptions<
    HooksResponse,
    Error,
    TData
  > => ({
    queryKey:
      daoPreProposeMultipleQueryKeys.proposalSubmittedHooks(contractAddress),
    queryFn: async () => {
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposalSubmittedHooks()
    },
    ...options,
  }),
  queryExtension: <TData = Binary>({
    chainId,
    contractAddress,
    args,
    options,
  }: DaoPreProposeMultipleQueryExtensionQuery<TData>): UseQueryOptions<
    Binary,
    Error,
    TData
  > => ({
    queryKey: daoPreProposeMultipleQueryKeys.queryExtension(
      contractAddress,
      args
    ),
    queryFn: async () => {
      return new DaoPreProposeMultipleQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).queryExtension({
        msg: args.msg,
      })
    },
    ...options,
  }),
  info: contractQueries.info,
}
export interface DaoPreProposeMultipleReactQuery<TResponse, TData = TResponse> {
  chainId: string
  contractAddress: string
  options?: Omit<
    UseQueryOptions<TResponse, Error, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  > & {
    initialData?: undefined
  }
}
export interface DaoPreProposeMultipleQueryExtensionQuery<TData>
  extends DaoPreProposeMultipleReactQuery<Binary, TData> {
  args: {
    msg: Empty
  }
}
export interface DaoPreProposeMultipleProposalSubmittedHooksQuery<TData>
  extends DaoPreProposeMultipleReactQuery<HooksResponse, TData> {}
export interface DaoPreProposeMultipleCanProposeQuery<TData>
  extends DaoPreProposeMultipleReactQuery<Boolean, TData> {
  args: {
    address: string
  }
}
export interface DaoPreProposeMultipleDepositInfoQuery<TData>
  extends DaoPreProposeMultipleReactQuery<DepositInfoResponse, TData> {
  args: {
    proposalId: number
  }
}
export interface DaoPreProposeMultipleConfigQuery<TData>
  extends DaoPreProposeMultipleReactQuery<Config, TData> {}
export interface DaoPreProposeMultipleDaoQuery<TData>
  extends DaoPreProposeMultipleReactQuery<Addr, TData> {}
export interface DaoPreProposeMultipleProposalModuleQuery<TData>
  extends DaoPreProposeMultipleReactQuery<Addr, TData> {}
