/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { QueryClient, UseQueryOptions } from '@tanstack/react-query'

import {
  Addr,
  Config,
  HooksResponse,
  InfoResponse,
  ProposalCreationPolicy,
  ProposalListResponse,
  ProposalResponse,
  VoteListResponse,
  VoteResponse,
} from '@dao-dao/types/contracts/DaoProposalSingle.v2'
import { getCosmWasmClientForChainId } from '@dao-dao/utils'

import { DaoProposalSingleV2QueryClient } from '../../../contracts/DaoProposalSingle.v2'
import { contractQueries } from '../contract'
import { indexerQueries } from '../indexer'

export const daoProposalSingleV2QueryKeys = {
  contract: [
    {
      contract: 'daoProposalSingleV2',
    },
  ] as const,
  address: (contractAddress: string) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.contract[0],
        address: contractAddress,
      },
    ] as const,
  config: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'config',
        args,
      },
    ] as const,
  proposal: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'proposal',
        args,
      },
    ] as const,
  listProposals: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'list_proposals',
        args,
      },
    ] as const,
  reverseProposals: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'reverse_proposals',
        args,
      },
    ] as const,
  getVote: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'get_vote',
        args,
      },
    ] as const,
  listVotes: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'list_votes',
        args,
      },
    ] as const,
  proposalCount: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'proposal_count',
        args,
      },
    ] as const,
  proposalCreationPolicy: (
    contractAddress: string,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'proposal_creation_policy',
        args,
      },
    ] as const,
  proposalHooks: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'proposal_hooks',
        args,
      },
    ] as const,
  voteHooks: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'vote_hooks',
        args,
      },
    ] as const,
  dao: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'dao',
        args,
      },
    ] as const,
  info: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'info',
        args,
      },
    ] as const,
  nextProposalId: (contractAddress: string, args?: Record<string, unknown>) =>
    [
      {
        ...daoProposalSingleV2QueryKeys.address(contractAddress)[0],
        method: 'next_proposal_id',
        args,
      },
    ] as const,
}
export const daoProposalSingleV2Queries = {
  config: <TData = Config>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: DaoProposalSingleV2ConfigQuery<TData>
  ): UseQueryOptions<Config, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.config(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/config',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).config()
    },
    ...options,
  }),
  proposal: <TData = ProposalResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoProposalSingleV2ProposalQuery<TData>
  ): UseQueryOptions<ProposalResponse, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.proposal(contractAddress, args),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/proposal',
            args: {
              id: args.proposalId,
            },
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposal({
        proposalId: args.proposalId,
      })
    },
    ...options,
  }),
  listProposals: <TData = ProposalListResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoProposalSingleV2ListProposalsQuery<TData>
  ): UseQueryOptions<ProposalListResponse, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.listProposals(contractAddress, args),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return {
          proposals: await queryClient.fetchQuery(
            indexerQueries.queryContract(queryClient, {
              chainId,
              contractAddress,
              formula: 'daoProposalSingle/listProposals',
              args,
            })
          ),
        }
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).listProposals({
        limit: args.limit,
        startAfter: args.startAfter,
      })
    },
    ...options,
  }),
  reverseProposals: <TData = ProposalListResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoProposalSingleV2ReverseProposalsQuery<TData>
  ): UseQueryOptions<ProposalListResponse, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.reverseProposals(
      contractAddress,
      args
    ),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return {
          proposals: await queryClient.fetchQuery(
            indexerQueries.queryContract(queryClient, {
              chainId,
              contractAddress,
              formula: 'daoProposalSingle/reverseProposals',
              args,
            })
          ),
        }
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).reverseProposals({
        limit: args.limit,
        startBefore: args.startBefore,
      })
    },
    ...options,
  }),
  getVote: <TData = VoteResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoProposalSingleV2GetVoteQuery<TData>
  ): UseQueryOptions<VoteResponse, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.getVote(contractAddress, args),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return {
          vote: await queryClient.fetchQuery(
            indexerQueries.queryContract(queryClient, {
              chainId,
              contractAddress,
              formula: 'daoProposalSingle/vote',
              args,
            })
          ),
        }
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).getVote({
        proposalId: args.proposalId,
        voter: args.voter,
      })
    },
    ...options,
  }),
  listVotes: <TData = VoteListResponse>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: DaoProposalSingleV2ListVotesQuery<TData>
  ): UseQueryOptions<VoteListResponse, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.listVotes(contractAddress, args),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return {
          votes: await queryClient.fetchQuery(
            indexerQueries.queryContract(queryClient, {
              chainId,
              contractAddress,
              formula: 'daoProposalSingle/listVotes',
              args,
            })
          ),
        }
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).listVotes({
        limit: args.limit,
        proposalId: args.proposalId,
        startAfter: args.startAfter,
      })
    },
    ...options,
  }),
  proposalCount: <TData = number>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      options,
    }: DaoProposalSingleV2ProposalCountQuery<TData>
  ): UseQueryOptions<number, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.proposalCount(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/proposalCount',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposalCount()
    },
    ...options,
  }),
  proposalCreationPolicy: <TData = ProposalCreationPolicy>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      options,
    }: DaoProposalSingleV2ProposalCreationPolicyQuery<TData>
  ): UseQueryOptions<ProposalCreationPolicy, Error, TData> => ({
    queryKey:
      daoProposalSingleV2QueryKeys.proposalCreationPolicy(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/creationPolicy',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposalCreationPolicy()
    },
    ...options,
  }),
  proposalHooks: <TData = HooksResponse>({
    chainId,
    contractAddress,
    options,
  }: DaoProposalSingleV2ProposalHooksQuery<TData>): UseQueryOptions<
    HooksResponse,
    Error,
    TData
  > => ({
    queryKey: daoProposalSingleV2QueryKeys.proposalHooks(contractAddress),
    queryFn: async () => {
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).proposalHooks()
    },
    ...options,
  }),
  voteHooks: <TData = HooksResponse>({
    chainId,
    contractAddress,
    options,
  }: DaoProposalSingleV2VoteHooksQuery<TData>): UseQueryOptions<
    HooksResponse,
    Error,
    TData
  > => ({
    queryKey: daoProposalSingleV2QueryKeys.voteHooks(contractAddress),
    queryFn: async () => {
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).voteHooks()
    },
    ...options,
  }),
  dao: <TData = Addr>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: DaoProposalSingleV2DaoQuery<TData>
  ): UseQueryOptions<Addr, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.dao(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/dao',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).dao()
    },
    ...options,
  }),
  info: contractQueries.info,
  nextProposalId: <TData = number>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      options,
    }: DaoProposalSingleV2NextProposalIdQuery<TData>
  ): UseQueryOptions<number, Error, TData> => ({
    queryKey: daoProposalSingleV2QueryKeys.nextProposalId(contractAddress),
    queryFn: async () => {
      try {
        // Attempt to fetch data from the indexer.
        return await queryClient.fetchQuery(
          indexerQueries.queryContract(queryClient, {
            chainId,
            contractAddress,
            formula: 'daoProposalSingle/nextProposalId',
          })
        )
      } catch (error) {
        console.error(error)
      }

      // If indexer query fails, fallback to contract query.
      return new DaoProposalSingleV2QueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).nextProposalId()
    },
    ...options,
  }),
}
export interface DaoProposalSingleV2ReactQuery<TResponse, TData = TResponse> {
  chainId: string
  contractAddress: string
  options?: Omit<
    UseQueryOptions<TResponse, Error, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  > & {
    initialData?: undefined
  }
}
export interface DaoProposalSingleV2NextProposalIdQuery<TData>
  extends DaoProposalSingleV2ReactQuery<number, TData> {}
export interface DaoProposalSingleV2InfoQuery<TData>
  extends DaoProposalSingleV2ReactQuery<InfoResponse, TData> {}
export interface DaoProposalSingleV2DaoQuery<TData>
  extends DaoProposalSingleV2ReactQuery<Addr, TData> {}
export interface DaoProposalSingleV2VoteHooksQuery<TData>
  extends DaoProposalSingleV2ReactQuery<HooksResponse, TData> {}
export interface DaoProposalSingleV2ProposalHooksQuery<TData>
  extends DaoProposalSingleV2ReactQuery<HooksResponse, TData> {}
export interface DaoProposalSingleV2ProposalCreationPolicyQuery<TData>
  extends DaoProposalSingleV2ReactQuery<ProposalCreationPolicy, TData> {}
export interface DaoProposalSingleV2ProposalCountQuery<TData>
  extends DaoProposalSingleV2ReactQuery<number, TData> {}
export interface DaoProposalSingleV2ListVotesQuery<TData>
  extends DaoProposalSingleV2ReactQuery<VoteListResponse, TData> {
  args: {
    limit?: number
    proposalId: number
    startAfter?: string
  }
}
export interface DaoProposalSingleV2GetVoteQuery<TData>
  extends DaoProposalSingleV2ReactQuery<VoteResponse, TData> {
  args: {
    proposalId: number
    voter: string
  }
}
export interface DaoProposalSingleV2ReverseProposalsQuery<TData>
  extends DaoProposalSingleV2ReactQuery<ProposalListResponse, TData> {
  args: {
    limit?: number
    startBefore?: number
  }
}
export interface DaoProposalSingleV2ListProposalsQuery<TData>
  extends DaoProposalSingleV2ReactQuery<ProposalListResponse, TData> {
  args: {
    limit?: number
    startAfter?: number
  }
}
export interface DaoProposalSingleV2ProposalQuery<TData>
  extends DaoProposalSingleV2ReactQuery<ProposalResponse, TData> {
  args: {
    proposalId: number
  }
}
export interface DaoProposalSingleV2ConfigQuery<TData>
  extends DaoProposalSingleV2ReactQuery<Config, TData> {}
